services:
  postgres:
    image: ankane/pgvector:latest
    container_name: smart_pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello098
      POSTGRES_DB: smart_research
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: